# Generated by Django 2.2.4 on 2023-02-22 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='标题')),
                ('context', models.CharField(max_length=500, verbose_name='内容')),
                ('postType', models.CharField(choices=[('lostAndFound', 'lostAndFound'), ('anecdoteForum', 'anecdoteForum'), ('driftBottle', 'driftBottle'), ('eventInformation', 'eventInformation'), ('loveWall', 'loveWall')], max_length=50, verbose_name='类型')),
                ('publishDate', models.DateField(default=django.utils.timezone.now, max_length=20, verbose_name='发布日期')),
                ('likesNum', models.IntegerField(default=0, verbose_name='点赞数')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerNum', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'post',
                'db_table': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='forum.Post', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='点赞者')),
            ],
            options={
                'verbose_name': 'postLike',
                'verbose_name_plural': 'postLike',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='Photos/PostsPhoto', verbose_name='帖子图片')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postImages', to='forum.Post', verbose_name='帖子图片')),
            ],
            options={
                'verbose_name': 'postIMG',
                'verbose_name_plural': 'postIMG',
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='', max_length=500, verbose_name='内容')),
                ('commitOwner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitConmmits', to='forum.Commit', verbose_name='主评论')),
                ('postOwner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postConmmits', to='forum.Post', verbose_name='主帖子')),
                ('userOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userOwner', to=settings.AUTH_USER_MODEL, verbose_name='帖子所有者')),
            ],
            options={
                'verbose_name': 'Commit',
                'verbose_name_plural': 'Commit',
            },
        ),
    ]
