# Generated by Django 2.2.4 on 2023-01-18 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=45, verbose_name='标题')),
                ('context', models.TextField(verbose_name='内容')),
                ('postType', models.CharField(choices=[('lostAndFound', 'lostAndFound'), ('anecdoteForum', 'anecdoteForum'), ('driftBottle', 'driftBottle'), ('eventInformation', 'eventInformation'), ('loveWall', 'loveWall')], max_length=50, verbose_name='类型')),
                ('publishDate', models.DateField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('ownerNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'db_table': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='Photos/PostsPhoto', verbose_name='帖子图片')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImgs', to='forum.Post', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
            },
        ),
    ]
