# Generated by Django 2.2.4 on 2023-01-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': '帖子图片', 'verbose_name_plural': '帖子图片'},
        ),
    ]
