# Generated by Django 2.2.4 on 2023-02-26 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20230223_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postowner', to='forum.Post', verbose_name='帖子')),
                ('userowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userowner', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'userCollection',
                'verbose_name_plural': 'userCollection',
            },
        ),
    ]
