# Generated by Django 2.2.4 on 2023-01-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20230118_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'post'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'postIMG', 'verbose_name_plural': 'postIMG'},
        ),
        migrations.AddField(
            model_name='post',
            name='likesNum',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
            preserve_default=False,
        ),
    ]
