# Generated by Django 2.2.4 on 2023-01-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20230125_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PostImage',
            field=models.ImageField(blank=True, upload_to='Photos/PostsPhoto', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likesNum',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
