# Generated by Django 2.2.4 on 2023-03-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_usercollection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercollection',
            old_name='postowner',
            new_name='postOwner',
        ),
        migrations.RenameField(
            model_name='usercollection',
            old_name='userowner',
            new_name='userOwner',
        ),
        migrations.AddField(
            model_name='commit',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='postlike',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
