# Generated by Django 2.2.4 on 2023-01-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20230125_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostImage',
            field=models.ImageField(upload_to='Photos/PostsPhoto', verbose_name='图片'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='Photos/PostsPhoto', verbose_name='帖子图片')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImgs', to='forum.Post', verbose_name='帖子')),
            ],
            options={
                'verbose_name': 'postIMG',
                'verbose_name_plural': 'postIMG',
            },
        ),
    ]
