# Generated by Django 2.2.4 on 2023-03-05 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_auto_20230303_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='消息内容')),
                ('hasReaded', models.BooleanField(default=False, verbose_name='是否查看')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postId', to='forum.Post')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='poster', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
