# Generated by Django 2.2.4 on 2023-01-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20230125_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='PostImage',
        ),
    ]
