# Generated by Django 2.2.4 on 2023-01-26 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_post_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='product',
        ),
        migrations.AddField(
            model_name='postimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postImages', to='forum.Post', verbose_name='帖子'),
            preserve_default=False,
        ),
    ]
