# Generated by Django 2.2.4 on 2023-01-26 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20230126_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ownerNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerNum', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
    ]
