# Generated by Django 2.2.4 on 2023-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20230421_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='isChecked',
            field=models.BooleanField(default=False, verbose_name='是否审核'),
        ),
        migrations.AddField(
            model_name='post',
            name='isChecked',
            field=models.BooleanField(default=False, verbose_name='是否审核'),
        ),
    ]
