# Generated by Django 2.2.4 on 2023-01-26 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20230126_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publishTime',
            field=models.TimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publishDate',
            field=models.DateField(default=django.utils.timezone.now, max_length=20, verbose_name='发布日期'),
        ),
    ]
