# Generated by Django 2.2.4 on 2023-01-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_remove_post_publishtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ownerNum',
            new_name='owner',
        ),
    ]
