# Generated by Django 2.2.4 on 2023-04-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20230422_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='postOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postConmmits', to='forum.Post', verbose_name='主帖子'),
        ),
    ]
