# Generated by Django 2.2.4 on 2023-04-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20230422_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='isChecked',
            field=models.BooleanField(default=False, verbose_name='是否审核通过'),
        ),
    ]
