# Generated by Django 2.2.4 on 2023-02-02 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20230129_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postImages', to='forum.Post', verbose_name='帖子图片'),
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitConmmits', to='forum.Commit', verbose_name='评论')),
                ('postOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postConmmits', to='forum.Post', verbose_name='评论')),
            ],
            options={
                'verbose_name': 'Commit',
                'verbose_name_plural': 'Commit',
            },
        ),
    ]
