# Generated by Django 2.2.4 on 2023-02-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20230202_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='context',
            field=models.CharField(default='', max_length=500, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='context',
            field=models.CharField(max_length=500, verbose_name='内容'),
        ),
    ]
