# Generated by Django 2.2.4 on 2023-02-02 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20230202_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='commitOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitConmmits', to='forum.Commit', verbose_name='主评论'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='postOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postConmmits', to='forum.Post', verbose_name='主帖子'),
        ),
    ]
