# Generated by Django 2.2.4 on 2023-02-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_postlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commit',
        ),
    ]
