# Generated by Django 2.2.4 on 2023-02-15 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0018_delete_commit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='', max_length=500, verbose_name='内容')),
                ('commitOwner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitConmmits', to='forum.Commit', verbose_name='主评论')),
                ('postOwner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postConmmits', to='forum.Post', verbose_name='主帖子')),
                ('userOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userOwner', to=settings.AUTH_USER_MODEL, verbose_name='帖子所有者')),
            ],
            options={
                'verbose_name': 'Commit',
                'verbose_name_plural': 'Commit',
            },
        ),
    ]
