# Generated by Django 2.2.4 on 2023-01-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='headPortrait',
            field=models.ImageField(null=True, upload_to='Photos/headPortrait', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personalSignature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
