# Generated by Django 2.2.4 on 2023-01-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.IntegerField(max_length=128, unique=True, verbose_name='username'),
        ),
    ]
