# Generated by Django 2.2.4 on 2023-01-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230126_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.IntegerField(unique=True, verbose_name='username'),
        ),
    ]
