# Generated by Django 2.2.4 on 2023-01-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230126_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='personalSignature',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='个性签名'),
        ),
    ]
