# Generated by Django 2.2.4 on 2023-03-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hasReaded',
            field=models.BooleanField(default=False, verbose_name='是否查看'),
        ),
    ]
