# Generated by Django 2.2.4 on 2023-03-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230304_2308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
