# Generated by Django 2.2.4 on 2023-03-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='暂未填写', max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personalSignature',
            field=models.CharField(blank=True, default='暂未填写', max_length=500, null=True, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='暂未填写', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qq',
            field=models.CharField(blank=True, default='暂未填写', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wechat',
            field=models.CharField(blank=True, default='暂未填写', max_length=128, null=True),
        ),
    ]
