# Generated by Django 2.2.4 on 2023-03-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230313_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='男', max_length=45, null=True),
        ),
    ]
